name: Schedule Actions

on:
  repository_dispatch:
    types: [build]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env }}





# crontab guru which explains necessary info about "* * * * *"
# repository_dispatch only works on main(master) branch

#  schedule:
#    - cron: "0/5 * * * *"