name: Secret Actions

on:
  pull_request:
env:
  SOME_SECRET: ${{ secrets.SOME_SECRET }}

jobs:
  log-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Log secrets
        run: |
          echo "SOME_SECRET: ${SOME_SECRET}"
          echo "GITHUB_TOKEN: ${GITHUB_TOKEN}"